### ISSUE TITLE
Potential aliasing issue (or perf optim)

### ISSUE THREAD

**Issue by mratsim** [benjaminion/c-kzg#1]
In this location you copy `out[i]` and then reuse it in add/sub

https://github.com/benjaminion/c-kzg/blob/f93c33c2db2b6942bcfcf0003b36d3f374a5b8d6/src/fft_fr.c#L36-L51

If you reorder the substraction and addition, you can safely directly reuse `out[i]` without copy. BLST should handle aliasing fine.

```C
         for (uint64_t i = 0; i < half; i++) { 
             blst_fr y_times_root; 
             blst_fr_mul(&y_times_root, &out[i + half], &roots[i * roots_stride]);
             blst_fr_sub(&out[i + half], &out[i], &y_times_root);  // do substraction before `out[i]` is updated
             blst_fr_add(&out[i], &out[i], &y_times_root); 
```

**Comment by benjaminion** [comment]
Nice one, thanks! Adopted.

(I've been following the Go code fairly closely so far - will do a good optimisation pass later, but I'd have probably missed this one.)
